// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeygusajnbfqooaxqfay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFleWd1c2FqbmJmcW9vYXhxZmF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODM2MjAsImV4cCI6MjA2Mzc1OTYyMH0.DVHf9yOjk5MTU-32mpEyoUZnBqswYUCILv3VAPlWoOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);